### ISSUE TITLE
Celluloid cannot be required until here, or it will break Shoryuken's daemonization

### ISSUE THREAD

**Issue by marcagas** [phstc/shoryuken#117]
Hi Guys,

Just wondering if anyone has been using shoryuken and running it as a daemonize process. Running the command below to start shoryuken renders an error.

shoryuken -C config/initializers/shoryuken.yml -R -d --logfile log/shoryuken.log -P tmp/pids/shoryuken.pid

Celluloid cannot be required until here, or it will break Shoryuken's daemonization
/Users/marcthespark/.rvm/gems/ruby-2.1.2@ls-member/gems/shoryuken-1.0.2/lib/shoryuken/cli.rb:64:in `load_celluloid'
/Users/marcthespark/.rvm/gems/ruby-2.1.2@ls-member/gems/shoryuken-1.0.2/lib/shoryuken/cli.rb:38:in `run'
/Users/marcthespark/.rvm/gems/ruby-2.1.2@ls-member/gems/shoryuken-1.0.2/bin/shoryuken:6:in `<top (required)>'
/Users/marcthespark/.rvm/gems/ruby-2.1.2@ls-member/bin/shoryuken:23:in `load'
/Users/marcthespark/.rvm/gems/ruby-2.1.2@ls-member/bin/shoryuken:23:in `<main>'
/Users/marcthespark/.rvm/gems/ruby-2.1.2@ls-member/bin/ruby_executable_hooks:15:in `eval'
/Users/marcthespark/.rvm/gems/ruby-2.1.2@ls-member/bin/ruby_executable_hooks:15:in `<main>'

Regards,
Marc

**Comment by marcagas** [comment]
I think I have to close this issue, I found out that sucker_punch and shoryuken was requiring both the celluloid library. But instead of having two delayed job processors,  I'll just remove the other one.
