### ISSUE TITLE
Trying to utilize ActiveJob..

### ISSUE THREAD

**Issue by dyatlov** [phstc/shoryuken#165]
In my model:

```ruby
OembedParserJob.perform_later('post', id, url)
```

then when I execute shoryuken, I get:

```text
NoMethodError: undefined method `new' for nil:NilClass
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/shoryuken-2.0.2/lib/shoryuken/default_worker_registry.rb:23:in `fetch_worker'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/shoryuken-2.0.2/lib/shoryuken/processor.rb:17:in `process'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-12-17T19:48:08Z 26904 TID-grk7cnvbs ERROR: Process died, reason: undefined method `new' for nil:NilClass
```

**Comment by dyatlov** [comment]
sorry.. my mistake..

**Comment by gmalouf** [comment]
What was the cause of this?  I have a similar problem now calling perform_later.

**Comment by dyatlov** [comment]
Cause was due to old queued jobs in there..
I previously had them processed using Golang and used builtin
elasticbeanstalk mechanism to poll/post jobs..
Shoryuken uses another format of course so it couldn't parse jobs in format
I was sending them beforehand.

2015-12-23 18:17 GMT+02:00 Gary <notifications@github.com>:

**Comment by dyatlov** [comment]
so basically what you need is to check if you have anything old queued in SQS and delete it.
