### ISSUE TITLE
Support for centralized logging (daemon mode)

### ISSUE THREAD

**Issue by gmalouf** [phstc/shoryuken#167]
I attempted to configure the Shoryuken logger to send message to LogEntries in my shoryuken initializer as follows:
```
if Rails.env.staging?
  Shoryuken::Logging.logger = Le.new('staging-key')
elsif Rails.env.production?
  Shoryuken::Logging.logger = Le.new('prod-key')
end
```

However, when I ran my bundle exec command for staging (via anasible):

```
bundle exec shoryuken -R -C config/shoryuken.yml -P tmp/pids/shoryuken.pid -d
```

I receive the following error: 
failed: [ip_address] => {"changed": true, "cmd": ["bundle", "exec", "shoryuken", "-R", "-C", "config/shoryuken.yml", "-P", "tmp/pids/shoryuken.pid", "-d"], "delta": "0:00:11.429042", "end": "2015-12-23 16:00:24.312947", "rc": 1, "start": "2015-12-23 16:00:12.883905", "warnings": []}
stderr: You really should set a logfile if you're going to daemonize
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/shoryuken-2.0.2/lib/shoryuken/cli.rb:80:in `daemonize'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/shoryuken-2.0.2/lib/shoryuken/cli.rb:36:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/shoryuken-2.0.2/bin/shoryuken:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/shoryuken:23:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/shoryuken:23:in `<main>'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'

My goal is to not log locally but send everything to my central logging aggregator..

**Comment by gmalouf** [comment]
Unfortunately, it appears while I can set the new logger you still need to pass this command line option.  Closing, as it's probably not a real feature request.
