### ISSUE TITLE
Running both ActiveJob and non-ActiveJob workers

### ISSUE THREAD

**Issue by gmalouf** [phstc/shoryuken#168]
We are running in AWS, and are attempting to use Lambda to kick off our scheduled jobs.  Lambda sends messages to SNS, we then created a queue with a subscription to this SNS topic.  

I'm attempting to run shoryuken against two queues:

1. Queue that receives json messages from SNS
2. Queue for ActiveJob tasks

The worker that consumes from Queue #1 would simply parse out the job name from the json message, constantize and submit for execution as an active job.  Unfortunately, this worker never seems to be able to read from the queue:

 23 Dec 2015 12:46:49.085 [DK4IPH]NoMethodError: undefined method `new' for nil:NilClass
» 23 Dec 2015 12:46:49.085 [DK4IPH] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/shoryuken-2.0.2/lib/shoryuken/default_worker_registry.rb:23:in `fetch_worker'
» 23 Dec 2015 12:46:49.085 [DK4IPH] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/shoryuken-2.0.2/lib/shoryuken/processor.rb:17:in `process'
» 23 Dec 2015 12:46:49.085 [DK4IPH] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
» 23 Dec 2015 12:46:49.085 [DK4IPH] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
» 23 Dec 2015 12:46:49.085 [DK4IPH] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
» 23 Dec 2015 12:46:49.085 [DK4IPH] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
» 23 Dec 2015 12:46:49.085 [DK4IPH] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
» 23 Dec 2015 12:46:49.085 [07QTN0]2015-12-23 17:46:49 +0000 severity=ERROR, Actor crashed!
» 23 Dec 2015 12:46:49.085 [07QTN0]NoMethodError: undefined method `new' for nil:NilClass
» 23 Dec 2015 12:46:49.085 [07QTN0] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/shoryuken-2.0.2/lib/shoryuken/default_worker_registry.rb:23:in `fetch_worker'
» 23 Dec 2015 12:46:49.085 [07QTN0] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/shoryuken-2.0.2/lib/shoryuken/processor.rb:17:in `process'
» 23 Dec 2015 12:46:49.085 [07QTN0] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
» 23 Dec 2015 12:46:49.085 [07QTN0] /usr/local/rvm/gems/ruby-2.0.0-p643/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'

My gut tells me that the worker is not being picked up for one reason or another, but the output is not the biggest help for tracking this down..

**Comment by gmalouf** [comment]
For reference, I have my ActiveJobs defined under the app/jobs directory.  The non-active job worker is defined under the app/workers

**Comment by gmalouf** [comment]
I solved this - the instruction for the 'Active Job Queue Prefixing' option did not make it obvious to me that you still needed to prefix non-active-job workers (though not their configured queues).
