### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by marick** [phstc/shoryuken#193]
This looks like exactly what I need, but I'm having trouble getting started. I created this configuration:

```
619 $ tree
.
|-- shoryuken.yml
`-- worker.rb
```

Worker.rb contains exactly the example from the `README.rb`, except with the proper queue name. The config file is:
```
aws:
  access_key_id: xxx
  secret_access_key: xxx
  region:             us-east-1 
```

The result is:
```
628 $ bundle exec shoryuken -r worker.rb -C shoryuken.yml
/Users/marick/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- worker.rb (LoadError)
	from /Users/marick/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/marick/.rvm/gems/ruby-2.2.2/gems/shoryuken-2.0.4/lib/shoryuken/environment_loader.rb:159:in `require_workers'
	from /Users/marick/.rvm/gems/ruby-2.2.2/gems/shoryuken-2.0.4/lib/shoryuken/environment_loader.rb:25:in `load'
	from /Users/marick/.rvm/gems/ruby-2.2.2/gems/shoryuken-2.0.4/lib/shoryuken/environment_loader.rb:6:in `load'
	from /Users/marick/.rvm/gems/ruby-2.2.2/gems/shoryuken-2.0.4/lib/shoryuken/cli.rb:34:in `run'
	from /Users/marick/.rvm/gems/ruby-2.2.2/gems/shoryuken-2.0.4/bin/shoryuken:6:in `<top (required)>'

```

**Comment by marick** [comment]
I was definitely in the right directory:

```
629 $ ls -l worker.rb
-rw-r--r--  1 marick  503  391 Apr 15 17:04 worker.rb
```

**Comment by phstc** [comment]
Hey @marick 

Could you try `-r ./worker.rb`?
