### ISSUE TITLE
shoryuken hangs with no error messages

### ISSUE THREAD

**Issue by eni9889** [phstc/shoryuken#210]
Hi guys,

I am using the latest version from the github repo and after about 5 days of running the shoryuken hangs. I have god watching it but shoryuken does not exit and is also not polling for any messages. I do not have any DB connections etc. I am using a Poltergeist to perform some operations with phantomjs inside a Rails 4 app. Has anyone experienced this and is there anything else I can do to further look into the issue?

**Comment by mariokostelac** [comment]
Do you have any timeout set?

**Comment by timabdulla** [comment]
we also noticed a hang issue in production after about ~5 days.

**Comment by timabdulla** [comment]
@mariokostelac any way we can help diagnose this?

**Comment by eni9889** [comment]
Sorry for the late reply. I have concurrency set to 1 and delay set to 25. Nothing else

**Comment by mariokostelac** [comment]
@eni9889 @timabdulla could you provide any logs?

**Comment by timabdulla** [comment]
@mariokostelac no useful logs. just saw this happen again. i'll enable debug log level for one worker next deploy -- maybe there will be better information in there.

**Comment by mariokostelac** [comment]
@timabdulla thanks!

**Comment by phstc** [comment]
> I am using a Poltergeist to perform some operations with phantomjs inside a Rails 4 app.

I would blame that ^.  I had a similar issue with a similar setup a long time ago with Sidekiq. Unfortunately, at that time the strategy to fix that was basically to restart Sidekiq from time to time.

**Comment by timabdulla** [comment]
@mariokostelac I do not have the above mentioned setup (i.e. using Poltergeist), and I continue to experience recurrent silent hanging from workers across three separate services. I did `kill -sTTIN {worker_pid}` to get the thread backtraces. I'll paste that below. Sending the signal also causes the process to crash because the manager actor seems to have died, which may be a clue as to what is causing the hanging to occur.

```
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: Got TTIN signal\n","stream":"stdout","time":"2016-09-19T14:33:06.737764903Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: Thread TID-gorr13sq8 \n","stream":"stdout","time":"2016-09-19T14:33:06.737906959Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: /usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:192:in `backtrace'\n","stream":"stdout","time":"2016-09-19T14:33:06.738093416Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:192:in `block (2 levels) in handle_signal'\n","stream":"stdout","time":"2016-09-19T14:33:06.73810838Z"}
{"log":"/usr/local/lib/ruby/2.3.0/logger.rb:427:in `add'\n","stream":"stdout","time":"2016-09-19T14:33:06.738121942Z"}
{"log":"/usr/local/lib/ruby/2.3.0/logger.rb:489:in `info'\n","stream":"stdout","time":"2016-09-19T14:33:06.738128457Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:192:in `block in handle_signal'\n","stream":"stdout","time":"2016-09-19T14:33:06.738135138Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:189:in `each'\n","stream":"stdout","time":"2016-09-19T14:33:06.738157592Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:189:in `handle_signal'\n","stream":"stdout","time":"2016-09-19T14:33:06.738164774Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:56:in `run'\n","stream":"stdout","time":"2016-09-19T14:33:06.738170006Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/bin/shoryuken:6:in `\u003ctop (required)\u003e'\n","stream":"stdout","time":"2016-09-19T14:33:06.738175519Z"}
{"log":"/usr/local/bundle/bin/shoryuken:16:in `load'\n","stream":"stdout","time":"2016-09-19T14:33:06.738184299Z"}
{"log":"/usr/local/bundle/bin/shoryuken:16:in `\u003cmain\u003e'\n","stream":"stdout","time":"2016-09-19T14:33:06.738189685Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: Thread TID-gorrtb4ys \n","stream":"stdout","time":"2016-09-19T14:33:06.738200501Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: /usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'\n","stream":"stdout","time":"2016-09-19T14:33:06.738206551Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'\n","stream":"stdout","time":"2016-09-19T14:33:06.738211992Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'\n","stream":"stdout","time":"2016-09-19T14:33:06.738217327Z"}
{"log":"/usr/local/bundle/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'\n","stream":"stdout","time":"2016-09-19T14:33:06.738223438Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'\n","stream":"stdout","time":"2016-09-19T14:33:06.738229175Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'\n","stream":"stdout","time":"2016-09-19T14:33:06.738234992Z"}
{"log":"/usr/local/bundle/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'\n","stream":"stdout","time":"2016-09-19T14:33:06.738240962Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'\n","stream":"stdout","time":"2016-09-19T14:33:06.738246817Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'\n","stream":"stdout","time":"2016-09-19T14:33:06.738252684Z"}
{"log":"/usr/local/bundle/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'\n","stream":"stdout","time":"2016-09-19T14:33:06.738258846Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'\n","stream":"stdout","time":"2016-09-19T14:33:06.738265061Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'\n","stream":"stdout","time":"2016-09-19T14:33:06.738270629Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: Thread TID-gorrtamic \n","stream":"stdout","time":"2016-09-19T14:33:06.738276588Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: /usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'\n","stream":"stdout","time":"2016-09-19T14:33:06.738291031Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'\n","stream":"stdout","time":"2016-09-19T14:33:06.738298202Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'\n","stream":"stdout","time":"2016-09-19T14:33:06.73830387Z"}
{"log":"/usr/local/bundle/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'\n","stream":"stdout","time":"2016-09-19T14:33:06.738309472Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'\n","stream":"stdout","time":"2016-09-19T14:33:06.738315616Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'\n","stream":"stdout","time":"2016-09-19T14:33:06.738321334Z"}
{"log":"/usr/local/bundle/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'\n","stream":"stdout","time":"2016-09-19T14:33:06.738328774Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'\n","stream":"stdout","time":"2016-09-19T14:33:06.738344604Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'\n","stream":"stdout","time":"2016-09-19T14:33:06.738351811Z"}
{"log":"/usr/local/bundle/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'\n","stream":"stdout","time":"2016-09-19T14:33:06.738358086Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'\n","stream":"stdout","time":"2016-09-19T14:33:06.738364307Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'\n","stream":"stdout","time":"2016-09-19T14:33:06.738370403Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: Thread TID-gorrt9v8o \n","stream":"stdout","time":"2016-09-19T14:33:06.73837669Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: /usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'\n","stream":"stdout","time":"2016-09-19T14:33:06.738382372Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'\n","stream":"stdout","time":"2016-09-19T14:33:06.73838788Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'\n","stream":"stdout","time":"2016-09-19T14:33:06.738393127Z"}
{"log":"/usr/local/bundle/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'\n","stream":"stdout","time":"2016-09-19T14:33:06.738398392Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'\n","stream":"stdout","time":"2016-09-19T14:33:06.738403655Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'\n","stream":"stdout","time":"2016-09-19T14:33:06.738409192Z"}
{"log":"/usr/local/bundle/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'\n","stream":"stdout","time":"2016-09-19T14:33:06.738414572Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'\n","stream":"stdout","time":"2016-09-19T14:33:06.738420679Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'\n","stream":"stdout","time":"2016-09-19T14:33:06.738426298Z"}
{"log":"/usr/local/bundle/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'\n","stream":"stdout","time":"2016-09-19T14:33:06.738432189Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'\n","stream":"stdout","time":"2016-09-19T14:33:06.739301969Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'\n","stream":"stdout","time":"2016-09-19T14:33:06.739316972Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: Thread TID-gorrt99sg \n","stream":"stdout","time":"2016-09-19T14:33:06.739321681Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: /usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'\n","stream":"stdout","time":"2016-09-19T14:33:06.740150473Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'\n","stream":"stdout","time":"2016-09-19T14:33:06.740161218Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'\n","stream":"stdout","time":"2016-09-19T14:33:06.740165872Z"}
{"log":"/usr/local/bundle/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'\n","stream":"stdout","time":"2016-09-19T14:33:06.740169744Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'\n","stream":"stdout","time":"2016-09-19T14:33:06.74017481Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'\n","stream":"stdout","time":"2016-09-19T14:33:06.74017869Z"}
{"log":"/usr/local/bundle/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'\n","stream":"stdout","time":"2016-09-19T14:33:06.740184592Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'\n","stream":"stdout","time":"2016-09-19T14:33:06.74018919Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'\n","stream":"stdout","time":"2016-09-19T14:33:06.740198051Z"}
{"log":"/usr/local/bundle/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'\n","stream":"stdout","time":"2016-09-19T14:33:06.740202222Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'\n","stream":"stdout","time":"2016-09-19T14:33:06.740206147Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'\n","stream":"stdout","time":"2016-09-19T14:33:06.740209984Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: Thread TID-owy8etjw8 \n","stream":"stdout","time":"2016-09-19T14:33:06.740213831Z"}
{"log":"2016-09-19T14:33:06Z 1 TID-gorr13sq8 INFO: /usr/local/bundle/gems/airbrake-ruby-1.2.1/lib/airbrake-ruby/async_sender.rb:103:in `pop'\n","stream":"stdout","time":"2016-09-19T14:33:06.74021806Z"}
{"log":"/usr/local/bundle/gems/airbrake-ruby-1.2.1/lib/airbrake-ruby/async_sender.rb:103:in `block in spawn_worker'\n","stream":"stdout","time":"2016-09-19T14:33:06.740221938Z"}
{"log":"attempted to call a dead actor: manager\n","stream":"stderr","time":"2016-09-19T14:33:06.738463477Z"}
{"log":"/usr/local/bundle/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:9:in `method_missing'\n","stream":"stderr","time":"2016-09-19T14:33:06.740230586Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:198:in `handle_signal'\n","stream":"stderr","time":"2016-09-19T14:33:06.740234118Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:56:in `run'\n","stream":"stderr","time":"2016-09-19T14:33:06.740237696Z"}
{"log":"/usr/local/bundle/gems/shoryuken-2.0.11/bin/shoryuken:6:in `\u003ctop (required)\u003e'\n","stream":"stderr","time":"2016-09-19T14:33:06.740241453Z"}
{"log":"/usr/local/bundle/bin/shoryuken:16:in `load'\n","stream":"stderr","time":"2016-09-19T14:33:06.740245383Z"}
{"log":"/usr/local/bundle/bin/shoryuken:16:in `\u003cmain\u003e'\n","stream":"stderr","time":"2016-09-19T14:33:06.740249113Z"}
```
