### ISSUE TITLE
Shoryuken is looking for jobs in 'default' and 'development_default' queue

### ISSUE THREAD

**Issue by seban** [phstc/shoryuken#217]
It is my first try with shoryuken. I am using prefix in queue name but I have problem with consuming messages. 
```
$ docker-compose run --rm web shoryuken -R -C config/shoryuken.yml -v
2016-05-28T16:24:58Z 1 TID-gszqj9v6k WARN: The specified queue 'default' does not exist
2016-05-28T16:25:00Z 1 TID-gszqj9v6k INFO: Rails environment loaded
2016-05-28T16:25:00Z 1 TID-gszqj9v6k WARN: The specified queue 'default' does not exist
I, [2016-05-28T16:25:01.410130 #1]  INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
2016-05-28T16:25:01Z 1 TID-gszqj9v6k DEBUG: Firing 'startup' lifecycle event
2016-05-28T16:25:01Z 1 TID-gszqwhej8 INFO: Starting
2016-05-28T16:25:01Z 1 TID-gszqwhej8 DEBUG: Ready: 2, Busy: 0, Active Queues: [["default", 1], ["development_default", 1]]
2016-05-28T16:25:01Z 1 TID-gszqwfxhs DEBUG: Looking for new messages in 'default'
2016-05-28T16:25:01Z 1 TID-gszqwfxhs ERROR: Error fetching message: The specified queue 'default' does not exist
2016-05-28T16:25:01Z 1 TID-gszqwfxhs ERROR: /usr/local/bundle/gems/shoryuken-2.0.6/lib/shoryuken/queue.rb:11:in `rescue in initialize'
2016-05-28T16:25:01Z 1 TID-gszqwhej8 DEBUG: Ready: 2, Busy: 0, Active Queues: [["development_default", 1], ["default", 1]]
2016-05-28T16:25:01Z 1 TID-gszqwfxhs DEBUG: Looking for new messages in 'development_default'
2016-05-28T16:25:11Z 1 TID-gszqwfxhs DEBUG: No message found for 'development_default'
2016-05-28T16:25:11Z 1 TID-gszqwfxhs DEBUG: Fetcher for 'development_default' completed in 10159.956387999999 ms
2016-05-28T16:25:11Z 1 TID-gszqwhej8 DEBUG: Pausing 'development_default' for 10.0 seconds, because it's empty
2016-05-28T16:25:11Z 1 TID-gszqwhej8 DEBUG: Ready: 2, Busy: 0, Active Queues: [["default", 1]]
2016-05-28T16:25:11Z 1 TID-gszqwfxhs DEBUG: Looking for new messages in 'default'
2016-05-28T16:25:12Z 1 TID-gszqwfxhs ERROR: Error fetching message: The specified queue 'default' does not exist
2016-05-28T16:25:12Z 1 TID-gszqwfxhs ERROR: /usr/local/bundle/gems/shoryuken-2.0.6/lib/shoryuken/queue.rb:11:in `rescue in initialize'
2016-05-28T16:25:12Z 1 TID-gszqwhej8 DEBUG: Ready: 2, Busy: 0, Active Queues: [["default", 1]]
2016-05-28T16:25:12Z 1 TID-gszqwfxhs DEBUG: Looking for new messages in 'default'
2016-05-28T16:25:12Z 1 TID-gszqwfxhs ERROR: Error fetching message: The specified queue 'default' does not exist
2016-05-28T16:25:12Z 1 TID-gszqwfxhs ERROR: /usr/local/bundle/gems/shoryuken-2.0.6/lib/shoryuken/queue.rb:11:in `rescue in initialize'
2016-05-28T16:25:12Z 1 TID-gszqwhej8 DEBUG: Ready: 2, Busy: 0, Active Queues: [["default", 1]]
```

My `config/shoryuken.yml' is as follows
```
aws:
  access_key_id: no-no-no
  secret_access_key: more-no-no-no
  region: "eu-west-1"
  receive_message:
    wait_time_seconds: 10
concurrency: 2
delay: 10
queues:
  - default
```

If there are some messages in `development_default` they are properly consumed while log is flooded with information that `default` queue doesn't exist. How I should start shoryuken, am I missing something?

**Comment by phstc** [comment]
Hi @seban 

You need to manually created your in queue in AWS SQS, Shoryuken does not create it automatically.

Check out this article: https://github.com/phstc/shoryuken/wiki/Creating-a-queue

Cheers

**Comment by seban** [comment]
Hi @phstc thanks for reply but ... I am using queue name perfixing as wrote before and shoryken tries to fetch jobs from "development_default" (prefixed) and from "default" (without prefix). I don't want to use queues without prefix. So I assume shoryuken would not try to fetch jobs from "default" queue.
```
2016-05-28T16:25:01Z 1 TID-gszqwhej8 DEBUG: Ready: 2, Busy: 0, Active Queues: [["default", 1], ["development_default", 1]]
2016-05-28T16:25:01Z 1 TID-gszqwfxhs DEBUG: Looking for new messages in 'default'
2016-05-28T16:25:01Z 1 TID-gszqwfxhs ERROR: Error fetching message: The specified queue 'default' does not exist
```
