### ISSUE TITLE
Bug with ActiveJob?

### ISSUE THREAD

**Issue by glaucocustodio** [phstc/shoryuken#281]
Hi folks, I am with `'shoryuken', '~> 2.0'` and `''rails', ~> 5.0.0', '>= 5.0.0.1'` and have:

```ruby
# config/application.rb
config.active_job.queue_adapter = :shoryuken
```
```
# Procfile
worker: bundle exec shoryuken -R -C config/shoryuken.yml
```

Do you know why the job below returns `Process died, reason: undefined method 'new' for nil:NilClass` when I run `foreman start`?

```ruby
# jobs/foo_job.rb
class FooJob < ApplicationJob
  queue_as ENV["my_queue"]
  
  def perform(*args)
  end
end
```

If I remove `ActiveJob` like below it works:

```ruby
# jobs/foo_job.rb
class FooJob
  include Shoryuken::Worker
  shoryuken_options queue: ENV["my_queue"], auto_delete: true
  
  def perform(*args)
  end
end
```

Thanks.

**Comment by phstc** [comment]
@glaucocustodio I couldn't test it, but I'm not sure if ActiveJob supports `*` splat operator `def perform(*args)`, I've never tried it, could you try without it? What do you in your `ApplicationJob`?

**Comment by glaucocustodio** [comment]
I have an empty `ApplicationJob`.

```ruby
# jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end
```
I tried without the splat but doesn't work as well.
```ruby
...
def perform(args)
end
```

**Comment by phstc** [comment]
What's the version of Shoryuken you have in your Gemfile.lock?

**Comment by glaucocustodio** [comment]
`shoryuken (2.0.11)`.

I tested against `shoryuken (2.1.1)` but I get this when I run `foreman start`:
```
17:06:37 worker.1 | (<unknown>): did not find expected node content while parsing a flow node at line 13 column 6
17:06:37 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse'
17:06:37 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
17:06:37 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:325:in `parse'
17:06:37 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:252:in `load'
17:06:37 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shoryuken-2.1.1/lib/shoryuken/environment_loader.rb:49:in `config_file_options'
```

**Comment by phstc** [comment]
@glaucocustodio it seems to be an issue with your `shoryuken.yml`, could you share it?

**Comment by glaucocustodio** [comment]
```yml
aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  receive_message:
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp

concurrency: 1
delay: 0
queues:
  - [<%= ENV['my_queue'] %>, 1]
```

**Comment by phstc** [comment]
> flow node at line 13 column 6

It's complaining about the line 13, is `<%= ENV['my_queue'] %>` returning something?

**Comment by glaucocustodio** [comment]
`<%= ENV['my_queue'] %>` returns  `"my_queue"`. 

I tested with:

```yml
aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  receive_message:
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp

concurrency: 1
delay: 0
queues:
  - ["my_queue", 1]
```

And I get:

```
17:34:05 worker.1 | started with pid 49271
17:34:12 worker.1 | 2016-12-08T19:34:12Z 49271 TID-ouv11d72g WARN: [DEPRECATION] aws in shoryuken.yml is deprecated. Please use configure_server and configure_client in your initializer
17:34:12 worker.1 | missing region; use :region option or export region name to ENV['AWS_REGION']
17:34:12 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.28/lib/aws-sdk-core/plugins/regional_endpoint.rb:34:in `after_initialize'
17:34:12 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.28/lib/seahorse/client/base.rb:84:in `block in after_initialize'
17:34:12 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.28/lib/seahorse/client/base.rb:83:in `each'
17:34:12 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.28/lib/seahorse/client/base.rb:83:in `after_initialize'
17:34:12 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.28/lib/seahorse/client/base.rb:21:in `initialize'
17:34:12 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.28/lib/seahorse/client/base.rb:105:in `new'
17:34:12 worker.1 | /Users/glauco/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shoryuken-2.1.1/lib/shoryuken/aws_config.rb:49:in `sqs'
```

This is my `shoryuken.rb`:

```ruby
Shoryuken.configure_server do |config|
  # Replace Rails logger so messages are logged wherever Shoryuken is logging
  # Note: this entire block is only run by the processor, so we don't overwrite
  #       the logger when the app is running as usual.

  # Rails.logger = Shoryuken::Logging.logger
  # Rails.logger.level = Rails.application.config.log_level

  # config.server_middleware do |chain|
  #  chain.add Shoryuken::MyMiddleware
  # end
end
```

**Comment by phstc** [comment]
> 17:34:12 worker.1 | missing region; use :region option or export region name to ENV['AWS_REGION']

@glaucocustodio check what you sent to me ^

**Comment by glaucocustodio** [comment]
I have `ENV['AWS_REGION']` in my `.env` file.

**Comment by phstc** [comment]
@glaucocustodio try `<% raise ENV.inspect %>` in your `shoryuken.yml` to inspect all your ENVs.

**Comment by glaucocustodio** [comment]
Hum.. My env vars set in `.env` aren't being loaded with the worker.. Any suggestion?

**Comment by phstc** [comment]
Are you using `dotenv` or something like that to load `.env`?

**Comment by glaucocustodio** [comment]
I am using `dotenv-rails`, I read now that I need to place `gem 'dotenv-rails', '~> 2.1', require: 'dotenv/rails-now'` before the gems which use env vars. I put it on top of my `Gemfile` but I still can't get the vars loaded with the worker..

It seems Rails is not being loaded.. The `-R` / `--rails` should load Rails right? I am using `bundle exec shoryuken -R -C config/shoryuken.yml`.

**Comment by phstc** [comment]
Shoryuken does not load your application.rb. It loads only your workers, not your Rails app. You can use the dotenv cli to start Shoryuken `dotenv shoryuken ...`.

**Comment by h3poteto** [comment]
@glaucocustodio `shoryuken.yml` can not read variables in Rails, maybe  you can not use `dotenv-rails` now.
If you configure aws information in `dotenv-rails`, please use `configure_server` and `configure_client` in your `config/initializers/shoryuken.rb` like this:

```ruby
Shoryuken.configure_server do |config|
  config.aws = {
    sqs_endpoint: ENV["SQS_ENDPOINT"],
    secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
    access_key_id: ENV["AWS_ACCESS_KEY_ID"],
    region: ENV["AWS_REGION"]
  }
end

Shoryuken.configure_client do |config|
  config.aws = {
    sqs_endpoint: ENV["SQS_ENDPOINT"],
    secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
    access_key_id: ENV["AWS_ACCESS_KEY_ID"],
    region: ENV["AWS_REGION"]
  }
end
```

**Comment by glaucocustodio** [comment]
On README the aws setup is at `shoryuken.yml`, I think we should change to the initializer so.

I want to add `ApproximateReceiveCount` and `SentTimestamp`, is this correct?

```ruby
config.aws = {
    sqs_endpoint: ENV["SQS_ENDPOINT"],
    access_key_id: ENV["AWS_ACCESS_KEY_ID"],
    secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
    region: ENV["AWS_REGION"],
    receive_message: {
      attribute_names: ["ApproximateReceiveCount", "SentTimestamp"]
    }
}
```

I need to add `receive_message` to both server and client blocks?

How can I set the queues from my env vars? The `yml` below returns the error `(<unknown>): did not find expected node content while parsing a flow node at line 4 column 6`:

```yml
concurrency: 1
delay: 0
queues:
  - [<%= ENV["GENERATED_PROPOSAL_QUEUE"] %>, 1]
```

**Comment by glaucocustodio** [comment]
After looking into I figured out this way to set the things I need:

```ruby
Shoryuken.options[:concurrency] = 1
Shoryuken.options[:delay] = 4
Shoryuken.options[:queues] = [
  ENV["my_queue1"],
  ENV["my_queue2"]
]

Shoryuken.configure_server do |config|
  config.aws = {
    sqs_endpoint: ENV["AWS_SQS_ENDPOINT"],
    access_key_id: ENV["AWS_ACCESS_KEY_ID"],
    secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
    region: ENV["AWS_REGION"],
    receive_message: {
      attribute_names: ["ApproximateReceiveCount", "SentTimestamp"]
    }
  }

  Rails.logger = Shoryuken::Logging.logger
  Rails.logger.level = Rails.application.config.log_level
end

Shoryuken.configure_client do |config|
  config.aws = {
    sqs_endpoint: ENV["AWS_SQS_ENDPOINT"],
    access_key_id: ENV["AWS_ACCESS_KEY_ID"],
    secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
    region: ENV["AWS_REGION"],
    receive_message: {
      attribute_names: ["ApproximateReceiveCount", "SentTimestamp"]
    }
  }
end
```

I got rid of `shoryuken.yml` and I start the workers with `bundle exec shoryuken -R`.

The error `Process died, reason: undefined method `new' for nil:NilClass` was because I was giving an invalid json, maybe we could improve the error output..

Do I need to duplicate the `receive_message` key in both blocks?

Thanks.

**Comment by h3poteto** [comment]
@glaucocustodio Sorry for the delay in updating the README.

> Do I need to add receive_message to both server and client blocks? 

Those parameters are required in receive_message, so I think that it's enough to set it on `configure_client`.
