### ISSUE TITLE
Missing 'forwardable' require in Shoryuken v3.1.3

### ISSUE THREAD

**Issue by rbroemeling** [phstc/shoryuken#408]
On a clean install of Shoryuken v3.1.3, Shoryuken stacktraces like this:

```
[15:25:18][me@host:~/]$ /usr/local/bin/shoryuken
/usr/local/stow/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/shoryuken-3.1.3/lib/shoryuken.rb:33:in `<module:Shoryuken>': uninitialized constant Shoryuken::SingleForwardable (NameError)
	from /usr/local/stow/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/shoryuken-3.1.3/lib/shoryuken.rb:32:in `<top (required)>'
	from /usr/local/stow/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/stow/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/stow/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/shoryuken-3.1.3/lib/shoryuken/runner.rb:7:in `<top (required)>'
	from /usr/local/stow/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/shoryuken-3.1.3/bin/shoryuken:9:in `require_relative'
	from /usr/local/stow/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/shoryuken-3.1.3/bin/shoryuken:9:in `<top (required)>'
	from /usr/local/bin/shoryuken:22:in `load'
	from /usr/local/bin/shoryuken:22:in `<main>'
```

This is because 'forwardable' is not required in the Shoryuken source.

Adding `require 'forwardable'` to lib/shoryuken.rb fixes the problem, after which Shoryuken launches properly:

```
[15:26:48][me@host:~/]$ /usr/local/bin/shoryuken
2017-07-14T15:26:50Z 29349 TID-otghwlhwc WARN: No queues supplied
2017-07-14T15:26:50Z 29349 TID-otghwlhwc INFO: Starting
^C2017-07-14T15:26:52Z 29349 TID-otghwlhwc INFO: Received INT, will shutdown down
2017-07-14T15:26:52Z 29349 TID-otghwlhwc INFO: Shutting down
```

This issue manifests under ruby v2.3.3p222/rubygems v2.6.6.

**Comment by phstc** [comment]
Hi @rbroemeling 

Could you try `bundle exec /usr/local/bin/shoryuken`?

**Comment by rbroemeling** [comment]
@phstc The gem is installed on the system for this particular use case, it isn't bundled.

**Comment by phstc** [comment]
@rbroemeling you are right! I'm just waiting for C before merging #409. Thanks for reporting this 🍻

**Comment by rbroemeling** [comment]
@phstc Sure thing, thanks for the quick turn-around!

**Comment by phstc** [comment]
@rbroemeling 3.1.4 is out with your fix 🎉

**Comment by rbroemeling** [comment]
@phstc Confirmed that v3.1.4 fixes the problem, thanks very much!
