### ISSUE TITLE
uninitialized constant Rails (NameError) in shoryuken.yml 

### ISSUE THREAD

**Issue by amyyuqian** [phstc/shoryuken#422]
Hi,

First, thanks so much for making this gem! I'm having some issues running shoryuken with my current .yml file though.

When I run `bundle exec shoryuken -R -C config/shoryuken.yml` for my Rails app I get this error:

```
(erb):5:in `<main>': uninitialized constant Rails (NameError)
	from /Users/amyqian/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/erb.rb:850:in `eval'
	from /Users/amyqian/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/erb.rb:850:in `result'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/shoryuken-3.1.7/lib/shoryuken/environment_loader.rb:47:in `config_file_options'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/shoryuken-3.1.7/lib/shoryuken/environment_loader.rb:38:in `initialize_options'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/shoryuken-3.1.7/lib/shoryuken/environment_loader.rb:21:in `setup_options'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/shoryuken-3.1.7/lib/shoryuken/environment_loader.rb:7:in `setup_options'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/shoryuken-3.1.7/lib/shoryuken/runner.rb:32:in `run'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/shoryuken-3.1.7/bin/shoryuken:47:in `start'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/gems/shoryuken-3.1.7/bin/shoryuken:58:in `<top (required)>'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/bin/shoryuken:23:in `load'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/bin/shoryuken:23:in `<main>'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/amyqian/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```
shoryuken.yml
```
concurrency: 25
delay: 25
timeout: 8
queues:
  - <%= Rails.configuration.foo[:sqs_queue] %>
```

The `Rails.configuration.foo[:sqs_queue]` is set to be a different queue for each environment.

**Comment by amyyuqian** [comment]
Ah nevermind, I moved the setup into `/config/initiliazers/shoryuken.rb` and it works fine!
