### ISSUE TITLE
`shoryuken sqs` commands do not work with FIFO queues

### ISSUE THREAD

**Issue by adamthalhammer** [phstc/shoryuken#470]
Shoryuken is awesome, thank you to all the contributors for making it great.

We have come across a bug that affects the `sqs mv`, `sqs requeue`, and `sqs dump` commands. It looks like the shoryuken sqs cli is failing to pass through the required parameters of `MessageGroupId` and `MessageDeduplicationId`.

```ShellSession
$ bundle exec shoryuken sqs mv queue1.fifo queue2.fifo
bundler: failed to load command: shoryuken (./lib/ruby/gems/2.2.0/bin/shoryuken)
Aws::SQS::Errors::InvalidParameterValue: The request must contain the parameter MessageGroupId.
  ./lib/ruby/gems/2.2.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
  ./lib/ruby/gems/2.2.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  ./lib/ruby/gems/2.2.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  ./lib/ruby/gems/2.2.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  ./lib/ruby/gems/2.2.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  ./lib/ruby/gems/2.2.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  ./lib/ruby/gems/2.2.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/request.rb:70:in `send_request'
  ./lib/ruby/gems/2.2.0/gems/aws-sdk-sqs-1.3.0/lib/aws-sdk-sqs/client.rb:1766:in `send_message_batch'
  ./lib/ruby/gems/2.2.0/gems/shoryuken-3.2.0/bin/cli/sqs.rb:45:in `block in batch_send'
  ./lib/ruby/gems/2.2.0/gems/shoryuken-3.2.0/bin/cli/sqs.rb:44:in `each_slice'
  ./lib/ruby/gems/2.2.0/gems/shoryuken-3.2.0/bin/cli/sqs.rb:44:in `batch_send'
  ./lib/ruby/gems/2.2.0/gems/shoryuken-3.2.0/bin/cli/sqs.rb:172:in `mv'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor.rb:238:in `block in subcommand'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  ./lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  ./lib/ruby/gems/2.2.0/gems/shoryuken-3.2.0/bin/shoryuken:59:in `<top (required)>'
  ./lib/ruby/gems/2.2.0/bin/shoryuken:23:in `load'
  ./lib/ruby/gems/2.2.0/bin/shoryuken:23:in `<top (required)>'
```

**Comment by phstc** [comment]
@adamthalhammer great catch. We can probably add `attribute_names: ['All']` [here](https://github.com/phstc/shoryuken/blob/master/bin/cli/sqs.rb#L62), and re-send the same `MessageGroupId` and `MessageDeduplicationId`. But that might be trick with FIFO, if someone `requeue` or `mv` in less than 5 minutes, WDYT?

**Comment by adamthalhammer** [comment]
Thank you @phstc, I am happy to open a pull request if that would be useful.
I can think of a few ways to address that concern:

1. Document it and move on - one can assume that people who are using FIFO queues are aware of how `MessageDeduplicationId` works
1. Fail the command if the `SentTimestamp` of a message appears to be within the de-duplication window of ~ 5 minutes (not reliable, but could help avoid losing messages unintentionally)
1. (optionally?) generate a new `MessageDeduplicationId`

Maybe there is a better way?
