### ISSUE TITLE
SocketError causing backend process shutdown

### ISSUE THREAD

**Issue by waynerobinson** [phstc/shoryuken#474]
Hi

I'm not sure if this is expected behaviour or not, but when a machine loses Internet connectivity for a period of time and the dispatcher hits `SocketError` exceptions, the whole process shuts down.

I would've expected the service to just keep retrying indefinitely in this case (and I believe previous versions of Shoryuken did).

Is there anything I can configure to keep this retrying, even when connectivity fails?

Cheers.

Below is a stack trace:

```
08:40:35 shoryuken.1 | 2018-02-08T21:40:35Z 41434 TID-ouz0mca34 ERROR: Manager failed: Encountered a `SocketError` while attempting to connect to:
08:40:35 shoryuken.1 |
08:40:35 shoryuken.1 |   https://sqs.ap-southeast-2.amazonaws.com/911236210561/cashdeck-dev-wayne-seedewey
08:40:35 shoryuken.1 |
08:40:35 shoryuken.1 | This is typically the result of an invalid `:region` option or a
08:40:35 shoryuken.1 | poorly formatted `:endpoint` option.
08:40:35 shoryuken.1 |
08:40:35 shoryuken.1 | * Avoid configuring the `:endpoint` option directly. Endpoints are constructed
08:40:35 shoryuken.1 |   from the `:region`. The `:endpoint` option is reserved for connecting to
08:40:35 shoryuken.1 |   non-standard test endpoints.
08:40:35 shoryuken.1 |
08:40:35 shoryuken.1 | * Not every service is available in every region.
08:40:35 shoryuken.1 |
08:40:35 shoryuken.1 | * Never suffix region names with availability zones.
08:40:35 shoryuken.1 |   Use "us-east-1", not "us-east-1a"
08:40:35 shoryuken.1 |
08:40:35 shoryuken.1 | Known AWS regions include (not specific to this service):
08:40:35 shoryuken.1 |
08:40:35 shoryuken.1 | ap-northeast-1
08:40:35 shoryuken.1 | ap-northeast-2
08:40:35 shoryuken.1 | ap-south-1
08:40:35 shoryuken.1 | ap-southeast-1
08:40:35 shoryuken.1 | ap-southeast-2
08:40:35 shoryuken.1 | ca-central-1
08:40:35 shoryuken.1 | eu-central-1
08:40:35 shoryuken.1 | eu-west-1
08:40:35 shoryuken.1 | eu-west-2
08:40:35 shoryuken.1 | sa-east-1
08:40:35 shoryuken.1 | us-east-1
08:40:35 shoryuken.1 | us-east-2
08:40:35 shoryuken.1 | us-west-1
08:40:35 shoryuken.1 | us-west-2
08:40:35 shoryuken.1 | cn-north-1
08:40:35 shoryuken.1 | us-gov-west-1
08:40:35 shoryuken.1 |
08:40:35 shoryuken.1 | 2018-02-08T21:40:35Z 41434 TID-ouz0mca34 ERROR: /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/aws-sdk-core-2.6.48/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/aws-sdk-core-2.6.48/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/aws-sdk-core-2.6.48/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/aws-sdk-core-2.6.48/lib/seahorse/client/plugins/response_target.rb:21:in `call'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/aws-sdk-core-2.6.48/lib/seahorse/client/request.rb:70:in `send_request'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/aws-sdk-core-2.6.48/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/shoryuken-3.2.0/lib/shoryuken/queue.rb:43:in `receive_messages'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/shoryuken-3.2.0/lib/shoryuken/fetcher.rb:56:in `receive_messages'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/shoryuken-3.2.0/lib/shoryuken/fetcher.rb:17:in `block in fetch'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/shoryuken-3.2.0/lib/shoryuken/fetcher.rb:32:in `fetch_with_auto_retry'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/shoryuken-3.2.0/lib/shoryuken/fetcher.rb:12:in `fetch'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/shoryuken-3.2.0/lib/shoryuken/manager.rb:83:in `dispatch_single_messages'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/shoryuken-3.2.0/lib/shoryuken/manager.rb:45:in `dispatch'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/shoryuken-3.2.0/lib/shoryuken/manager.rb:31:in `block in dispatch_loop'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
08:40:35 shoryuken.1 | /Users/waynerobinson/.rvm/gems/ruby-2.4.3/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
08:40:35 shoryuken.1 | 2018-02-08T21:40:35Z 41434 TID-ouz0a1e2o INFO: Received USR1, will soft shutdown down
08:40:35 shoryuken.1 | 2018-02-08T21:40:35Z 41434 TID-ouz0a1e2o INFO: Shutting down
```

**Comment by phstc** [comment]
@waynerobinson it used to keep trying, then there was an issue asking for the other way around, since they were monitoring the process (which was running), but not consuming messages. 

There are trade offs with both approaches, keep running and shutdown. I usually monitor the queues based on their number of messages instead of the processes consuming them, but everybody can manage that differently.

**Comment by waynerobinson** [comment]
Yeah, I guess it doesn't really matter that much in our case as yes, we just have SystemD keep it operating. I guess I was just wondering if this was an intentional change or not.

Thanks. :)

**Comment by phstc** [comment]
@waynerobinson I have mixed feelings with both approaches.

**Comment by waynerobinson** [comment]
Sounds like something that should be configurable then. 😜

**Comment by phstc** [comment]
@waynerobinson if more people ask for! hehe
