### ISSUE TITLE
send_message failing with aws sdk 2

### ISSUE THREAD

**Issue by kookster** [phstc/shoryuken#55]
The current master now uses the aws sdk 2 for ruby, which is awesome.

However, when the signature for send_message is now to accept a single hash as an argument:
http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#send_message-instance_method

Here is how perform_async tries to call send_message:
```ruby
      def perform_async(body, options = {})
        options ||= {}
        options[:message_attributes] ||= {}
        options[:message_attributes]['shoryuken_class'] = {
          string_value: self.to_s,
          data_type: 'String'
        }

        queue = Shoryuken::Client.queues(get_shoryuken_options['queue'])
        queue.send_message(body, options)  # this is the wrong number of args
      end
```

Instead, the send_message call needs to look like this I think:
```ruby
      def perform_async(body, options = {})
        options ||= {}
        options[:message_attributes] ||= {}
        options[:message_attributes]['shoryuken_class'] = {
          string_value: self.to_s,
          data_type: 'String'
        }
        options[:message_body] = body

        queue = Shoryuken::Client.queues(get_shoryuken_options['queue'])
        queue.send_message(options)
      end
```

So when I try to send a message, I get the following error for the `send_message` on the sqs resource:
```
Failed to create new job and tasks: missing required parameter params[:message_body]
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.21/lib/seahorse/client/param_validator.rb:24:in `validate!'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.21/lib/seahorse/client/param_validator.rb:9:in `validate!'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.21/lib/seahorse/client/plugins/param_validation.rb:21:in `call'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.21/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.21/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.21/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.21/lib/seahorse/client/request.rb:70:in `send_request'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.21/lib/seahorse/client/base.rb:215:in `block (2 levels) in define_operation_methods'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.21.pre/lib/aws-sdk-resources/request.rb:24:in `call'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.21.pre/lib/aws-sdk-resources/operations.rb:41:in `call'
        /Users/andrew/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.21.pre/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
```

**Comment by kookster** [comment]
@leemhenson can you confirm I am using the right aws sdk version, and shed any light on why the `send_message` signature is not as expected?

**Comment by kookster** [comment]
BTW - I made the change above to my local copy of shoryuken, and it works, so that is the solution for what I am seeing locally.

**Comment by leemhenson** [comment]
https://github.com/phstc/shoryuken/pull/58

**Comment by phstc** [comment]
@kookster can I close this?

**Comment by kookster** [comment]
yes, #58 and #60 fix this.
