### ISSUE TITLE
Undefined method `delay`

### ISSUE THREAD

**Issue by qarol** [phstc/shoryuken#565]
I've got an error in latest `4.0.4` version. Looks like this issue is connected with #534.

```
gems/shoryuken-4.0.4/lib/shoryuken/launcher.rb:75:in `block in create_managers': undefined method `delay' for Shoryuken::Options:Class
Did you mean?  delegate (NoMethodError)
    from gems/shoryuken-4.0.4/lib/shoryuken/launcher.rb:72:in `each'
    from gems/shoryuken-4.0.4/lib/shoryuken/launcher.rb:72:in `map'
    from gems/shoryuken-4.0.4/lib/shoryuken/launcher.rb:72:in `create_managers'
    from gems/shoryuken-4.0.4/lib/shoryuken/launcher.rb:6:in `initialize'
    from gems/shoryuken-4.0.4/lib/shoryuken/runner.rb:43:in `new'
    from gems/shoryuken-4.0.4/lib/shoryuken/runner.rb:43:in `run'
    from gems/shoryuken-4.0.4/bin/shoryuken:42:in `start'
    from gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
    from gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    from gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    from gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
    from gems/shoryuken-4.0.4/bin/shoryuken:53:in `<top (required)>'
    from bin/shoryuken:23:in `load'
    from bin/shoryuken:23:in `<main>'
```

I use Shoryuken as default engine for ActiveJob.

:pushpin: #566

**Comment by phstc** [comment]
@qarol ah my totally bad. I need to add a test to ensure that in future. I created a PR for fixing it #566 as soon as it passes, I will :shipit:

**Comment by qarol** [comment]
@phstc Great! Thanks for feedback.

**Comment by phstc** [comment]
@qarol it should be good now. I've also yanked 4.0.4. You should be good downloading 4.0.3. Thanks for reporting.
