### ISSUE TITLE
ERB in config/shoryuken.yml?

### ISSUE THREAD

**Issue by MSCAU** [phstc/shoryuken#579]
I have read https://github.com/phstc/shoryuken/issues/559, where you recommend using separate YML files for dev and production. However in https://github.com/phstc/shoryuken/wiki/Complete-Shoryuken-Setup-for-Rails-5-with-ActiveJob you suggest using dotenv to load in ENVs.

I thought I had this working in both dev and prod:

```
concurrency: 15
queues:
- [<%= ENV['AWS_SQS_QUEUE'] %>, 1]
```

in combination with /.env.development.local:

`AWS_SQS_QUEUE=beatjosh-dev`

but the command 

`$ bundle exec shoryuken -R -C config/shoryuken.yml`

fails in dev with the following message:

```
Signal USR1 not supported
Signal TSTP not supported
Signal TTIN not supported
Traceback (most recent call last):
        16: from C:/RailsInstaller/Ruby25-x64/bin/shoryuken:23:in `<main>'
        15: from C:/RailsInstaller/Ruby25-x64/bin/shoryuken:23:in `load'
        14: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/bin/shoryuken:53:in `<top (required)>'
        13: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        12: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        11: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        10: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         9: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/bin/shoryuken:42:in `start'
         8: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/lib/shoryuken/runner.rb:31:in `run'
         7: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/lib/shoryuken/environment_loader.rb:7:in `setup_options'
         6: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/lib/shoryuken/environment_loader.rb:21:in `setup_options'
         5: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/lib/shoryuken/environment_loader.rb:38:in `initialize_options'
         4: from C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/lib/shoryuken/environment_loader.rb:47:in `config_file_options'
         3: from C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/psych.rb:263:in `load'
         2: from C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/psych.rb:350:in `parse'
         1: from C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/psych.rb:402:in `parse': (<unknown>): did not find expected node content while parsing a flow node at line 3 column 4 (Psych::SyntaxError)
```

So it appears that the YML interpreter is choking on the ERB code, which means that dotenv gem is doing nothing after all, and that I should just use separate YML files?

**Comment by phstc** [comment]
> I have read #559, where you recommend using separate YML files for dev and production. However in https://github.com/phstc/shoryuken/wiki/Complete-Shoryuken-Setup-for-Rails-5-with-ActiveJob you suggest using dotenv to load in ENVs.

There's no right or wrong approach, you can differentiate environments with separated files or environment variables, it is up to you and your setup. 

You need to make sure dotenv is being loaded before shoryuken. You can try to use the dotenv CLI, for example, `bundle exec dotenv shoryuken -R -C config/shoryuken.yml`
