### ISSUE TITLE
Shoryuken stuck & not consuming messages

### ISSUE THREAD

**Issue by kubibektas** [phstc/shoryuken#582]
Hi,

We are running shoryuken on Kubernetes (docker) with AWS SQS. Our pods suddenly stops consuming from time to time and they recover if we restart. I already checked past similar issues and digged down through logs & stack trace. Here is my findings, can you have a look ?

- shoryuken did not respond to `TTIN` command
- I followed the steps here https://blog.newrelic.com/engineering/debugging-stuck-ruby-processes-what-to-do-before-you-kill-9/ to get stack trace from threads. I got this log as a result: 

```
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/shoryuken-5.0.1/lib/shoryuken/manager.rb:31:in `block in dispatch_loop'
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/shoryuken-5.0.1/lib/shoryuken/manager.rb:38:in `dispatch'
  from /usr/src/app/vendor/bundle/ruby/2.6.0/gems/shoryuken-5.0.1/lib/shoryuken/manager.rb:38:in `sleep'
```
This is pretty much all i got, maybe it would mean something to you. I also have C level backtrace (`(gdb) t a a bt `) if you need,

Thanks !

**Comment by phstc** [comment]
Can you share your `shoryuken.yml` and how you start the CLI? What's the tail of the Shoryuken log when it freezes?
